export const ScreenIdsMapping = {
    "ao": "acceptOffer",
    "ro": "rejectoffer",
    "utd":'uploadDocument',
    "ud": "uploadDocument",
    "vd": "verifyDocument",
    "urgl": "uploadRegistration",
    "sol": "sendOffer",
    "arm": "documentRM",
    "abl": "documentBuddy",
    "bc": "documentBuddyConfirm",
    "swm": "sendWelcomeMail",
    "j": "confirmJoining",
    "rj": "rejectBuddy",
    "anb": "documentBuddy",
    "bd": "addBankDetails",
    "aa": "allocateAssets",
    "ha": "handoverAssets",
    "tef" : "trainingfeedback",
    "pef" :"probationfeedback",

}
